# Generated by Django 6.0.1 on 2026-02-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='street_address',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='exterior_number',
            field=models.CharField(default='S/N', max_length=50),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='interior_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='neighborhood',
            field=models.CharField(default='Desconocida', max_length=255),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='reference',
            field=models.TextField(blank=True, help_text='Ej. Casa blanca con portón azul', null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='street',
            field=models.CharField(default='Desconocida', max_length=255),
        ),
    ]
