# Generated by Django 6.0.1 on 2026-03-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_useraddress_street_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mp_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mp_preference_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('mercadopago', 'Mercado Pago')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('shipped', 'Enviado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
