# Generated by Django 6.0.1 on 2026-03-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_brand',
            field=models.CharField(blank=True, help_text='Ej: visa, mastercard, amex', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_last4',
            field=models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Mensaje de error cuando el pago falla', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('shipped', 'Enviado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
