# Generated by Django 6.0.1 on 2026-03-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_coupon_order_discount_shipping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='skydropx_shipment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
