apiVersion: v1
kind: Service
metadata:
  name: kuro-backend
  namespace: kuro
spec:
  type: NodePort
  selector:
    app: kuro-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30800
---
apiVersion: v1
kind: Service
metadata:
  name: kuro-frontend
  namespace: kuro
spec:
  type: NodePort
  selector:
    app: kuro-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
