apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuro-backend
  namespace: kuro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuro-backend
  template:
    metadata:
      labels:
        app: kuro-backend
    spec:
      initContainers:
        - name: run-migrations
          image: davidnicanor123/kuro-backend:1.0.3
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              python manage.py migrate --noinput
              python manage.py createsuperuser --noinput || true
          envFrom:
            - configMapRef:
                name: kuro-backend-config
            - secretRef:
                name: kuro-backend-secrets
      containers:
        - name: backend
          image: davidnicanor123/kuro-backend:1.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: kuro-backend-config
            - secretRef:
                name: kuro-backend-secrets
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "800m"
              memory: "512Mi"
