apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuro-backend
  namespace: kuro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kuro-backend
  template:
    metadata:
      labels:
        app: kuro-backend
    spec:
      # Distribuir equitativamente los pods entre los diferentes worker nodes
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: kuro-backend
      # Nunca ejecutar pods como root
      securityContext:
        runAsNonRoot: true
      initContainers:
        - name: run-migrations
          image: davidnicanor123/kuro-backend:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - |
              python manage.py migrate --noinput
              python manage.py createsuperuser --noinput || true
          envFrom:
            - configMapRef:
                name: kuro-backend-config
            - secretRef:
                name: kuro-backend-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      containers:
        - name: backend
          image: davidnicanor123/kuro-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: kuro-backend-config
            - secretRef:
                name: kuro-backend-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          readinessProbe:
            httpGet:
              path: /api/health/
              port: 8000
              httpHeaders:
                - name: Host
                  value: kurocustom.uk
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /api/health/
              port: 8000
              httpHeaders:
                - name: Host
                  value: kurocustom.uk
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "800m"
              memory: "512Mi"
