apiVersion: v1
kind: Service
metadata:
  name: kuro-backend
  namespace: kuro
spec:
  type: LoadBalancer
  selector:
    app: kuro-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kuro-frontend
  namespace: kuro
spec:
  type: LoadBalancer
  selector:
    app: kuro-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
